
import fs from 'fs';
import path from 'path';

// ═══════════════════════════════════════════════════════════════════════
// MEDIFLOW — PERSISTENT MOCK DATABASE
// This file uses a JSON file as the backbone to ensure that credentials
// generated by the admin survive server restarts and session logouts.
// ═══════════════════════════════════════════════════════════════════════

export interface StaffEntry {
    id: number;
    name: string;
    email: string;
    passwordHash: string;
    passwordPlain?: string; // Stored for mock login verification
    role: "doctor" | "pharmacist";
    specialization?: string | null;
    license?: string | null;
    isVerified?: boolean;
    isAuthorized?: boolean;
    pharmacyId?: string | null;
    phone?: string;
    experience?: string;
    qualifications?: string;
}

const DB_PATH = path.join(process.cwd(), 'src', 'lib', 'staff-db.json');

// Helper to read the physical database
const readDB = (): StaffEntry[] => {
    try {
        if (!fs.existsSync(DB_PATH)) {
            return [];
        }
        const data = fs.readFileSync(DB_PATH, 'utf8');
        return JSON.parse(data);
    } catch (err) {
        console.error("Critical: Failed to read from Staff Registry.", err);
        return [];
    }
};

// Helper to write to the physical database
const writeDB = (data: StaffEntry[]) => {
    try {
        fs.writeFileSync(DB_PATH, JSON.stringify(data, null, 2), 'utf8');
    } catch (err) {
        console.error("Critical: Failed to persist to Staff Registry.", err);
    }
};

// Singleton check to handle HMR in Next.js
declare global {
    var __mediflow_staff_registry: StaffEntry[] | undefined;
}

// Initial hydration from Disk
if (!global.__mediflow_staff_registry) {
    global.__mediflow_staff_registry = readDB();
}

export const staffRegistry = global.__mediflow_staff_registry!;

export const addStaff = (entry: StaffEntry) => {
    // Add to memory
    staffRegistry.push(entry);
    // Persist to disk
    writeDB(staffRegistry);
};

export const findStaffByEmail = (email: string) => {
    // Always work with fresh disk data to ensure cross-process integrity
    const currentDB = readDB();
    return currentDB.find(s => s.email.toLowerCase() === email.toLowerCase());
};

// Export raw registry for the GET route (sync with disk first)
export const getSafeRegistry = () => {
    return readDB();
};
