import { jsPDF } from "jspdf";

type MedicationLine = {
  name?: string;
  dosage?: string;
  duration?: string;
  timeLabel?: string;
};

type MedicationPdfPayload = {
  title: string;
  reportId: string;
  patientName: string;
  doctorLine: string;
  date: string;
  notes: string;
  medications: MedicationLine[];
  fileName: string;
};

export function downloadMedicationReportPdf(payload: MedicationPdfPayload) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 46;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxTextWidth = pageWidth - margin * 2;
  const pageBottom = doc.internal.pageSize.getHeight() - margin;

  let y = 58;

  const ensureSpace = (heightNeeded: number) => {
    if (y + heightNeeded <= pageBottom) return;
    doc.addPage();
    y = margin;
  };

  const writeLine = (text: string, size = 11, weight: "normal" | "bold" = "normal", gap = 16) => {
    ensureSpace(gap + 4);
    doc.setFont("times", weight);
    doc.setFontSize(size);
    doc.text(text, margin, y);
    y += gap;
  };

  const writeWrapped = (text: string, size = 11, weight: "normal" | "bold" = "normal", gap = 15) => {
    doc.setFont("times", weight);
    doc.setFontSize(size);
    const lines = doc.splitTextToSize(text, maxTextWidth) as string[];
    for (const line of lines) {
      ensureSpace(gap + 4);
      doc.text(line, margin, y);
      y += gap;
    }
  };

  const writeSectionTitle = (text: string) => {
    y += 8;
    writeLine(text, 13, "bold", 18);
  };

  // Red cross marker to emulate formal medical stationery.
  doc.setFillColor(210, 35, 35);
  doc.roundedRect(margin, 50, 34, 10, 2, 2, "F");
  doc.roundedRect(margin + 12, 38, 10, 34, 2, 2, "F");

  doc.setTextColor(178, 26, 26);
  doc.setFont("times", "bold");
  doc.setFontSize(31);
  doc.text("MEDIFLOW", margin + 46, 60);

  doc.setTextColor(20, 20, 20);
  doc.setFont("times", "bold");
  doc.setFontSize(12);
  doc.text("Integrated Health Platform", margin + 46, 78);
  doc.setFont("times", "normal");
  doc.setFontSize(10);
  doc.text("Digital Clinical Care Network", margin + 46, 93);

  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(2.5);
  doc.line(margin, 108, pageWidth - margin, 108);

  y = 145;

  const documentTitle = (payload.title || "MEDICAL REPORT").toUpperCase().includes("REPORT")
    ? "MEDICAL REPORT"
    : (payload.title || "MEDICAL REPORT").toUpperCase();

  doc.setFont("times", "bold");
  doc.setFontSize(24);
  doc.text(documentTitle, pageWidth / 2, y, { align: "center" });
  const titleWidth = doc.getTextWidth(documentTitle);
  doc.setLineWidth(1.2);
  doc.line((pageWidth - titleWidth) / 2, y + 5, (pageWidth + titleWidth) / 2, y + 5);

  y += 44;

  writeLine("To Whom It May Concern,", 13, "bold", 32);

  writeWrapped(
    `This is to certify that ${payload.patientName} was examined through MEDIFLOW on ${payload.date}. A medical assessment and medication plan were prepared by the attending doctor below.`,
    12,
    "normal",
    18
  );

  writeSectionTitle("Diagnosed:");
  writeWrapped(payload.notes || "No clinical notes provided.", 12, "normal", 18);

  writeSectionTitle("Medication Plan:");
  const meds = Array.isArray(payload.medications) ? payload.medications : [];
  if (meds.length === 0) {
    writeWrapped("No medications listed.", 12, "normal", 18);
  } else {
    meds.forEach((med, index) => {
      writeWrapped(
        `${index + 1}. ${med.name || "Unnamed medicine"} - ${med.dosage || "-"}; ${med.duration || "As prescribed"}; ${med.timeLabel || "Not set"}.`,
        12,
        "normal",
        18
      );
    });
  }

  writeSectionTitle("Remarks:");
  writeWrapped(
    "Patient is advised to follow the medication schedule exactly as prescribed and complete the full course for safe recovery.",
    12,
    "normal",
    18
  );

  writeSectionTitle("Record Details:");
  writeLine(`Report ID: ${payload.reportId}`, 11, "normal", 16);
  writeLine(`Patient: ${payload.patientName}`, 11, "normal", 16);
  writeLine(`Doctor: ${payload.doctorLine}`, 11, "normal", 16);
  writeLine(`Issued Date: ${payload.date}`, 11, "normal", 16);

  // Keep signature block near the lower area like a formal certificate.
  if (y < pageBottom - 120) {
    y = pageBottom - 120;
  } else {
    ensureSpace(120);
  }

  const signX = pageWidth - margin - 200;
  doc.setLineWidth(1);
  doc.line(signX, y, signX + 170, y);
  doc.setFont("times", "bold");
  doc.setFontSize(12);
  doc.text(payload.doctorLine, signX, y + 18);
  doc.setFont("times", "normal");
  doc.setFontSize(11);
  doc.text("Attending Physician", signX, y + 34);

  doc.setFont("times", "italic");
  doc.setFontSize(9);
  doc.text("Generated by MEDIFLOW", margin, pageBottom);

  const safeFileName = payload.fileName.toLowerCase().endsWith(".pdf")
    ? payload.fileName
    : `${payload.fileName}.pdf`;

  doc.save(safeFileName);
}
