
"use client";

import { useState, useEffect } from "react";
import { SidebarNav } from "@/components/layout/SidebarNav";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { 
  Users, 
  Calendar, 
  Activity, 
  Stethoscope, 
  Clock,
  CheckCircle2,
  Loader2,
  ChevronRight,
  TrendingUp,
  AlertTriangle,
  X
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useRouter } from "next/navigation";

export default function DoctorDashboard() {
  const { toast } = useToast();
  const router = useRouter();
  const [appointments, setAppointments] = useState<any[]>([]);
  const [todayAppointments, setTodayAppointments] = useState<any[]>([]);
  const [selectedPatient, setSelectedPatient] = useState<any>(null);
  const [doctorInfo, setDoctorInfo] = useState<any>(null);
  const [checkingIn, setCheckingIn] = useState<string | null>(null);

  useEffect(() => {
    const user = JSON.parse(localStorage.getItem("mediflow_current_user") || "{}");
    setDoctorInfo(user);

    const fetchAppts = () => {
      const savedAppts = JSON.parse(localStorage.getItem("mediflow_appointments") || "[]");
      const todayStr = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
      // Match by doctor email (synced from Admin Hub)
      const myAppts = savedAppts.filter((a: any) => a.doctorEmail?.toLowerCase() === user.email?.toLowerCase());
      setAppointments(myAppts);
      const today = myAppts.filter((a: any) => a.date === todayStr);
      setTodayAppointments(today);
    };

    fetchAppts();
    const interval = setInterval(fetchAppts, 5000);
    return () => clearInterval(interval);
  }, []);

  const handleCheckIn = (id: string) => {
    setCheckingIn(id);
    setTimeout(() => {
      const savedAppts = JSON.parse(localStorage.getItem("mediflow_appointments") || "[]");
      const updated = savedAppts.map((a: any) => 
        String(a.id) === String(id) ? { ...a, status: "Arrived" } : a
      );
      localStorage.setItem("mediflow_appointments", JSON.stringify(updated));
      setCheckingIn(null);
      toast({
        title: "Patient Arrived",
        description: "Clinical session can now proceed.",
      });
    }, 1500);
  };

  const handlePrescribe = (id: string) => {
    router.push(`/dashboard/doctor/diagnose/${id}`);
  };

  return (
    <div className="flex min-h-screen">
      <SidebarNav role="doctor" />
      
      <main className="flex-1 p-8 bg-background">
        <header className="mb-8 flex justify-between items-start">
          <div>
            <h1 className="text-4xl font-headline font-bold text-primary mb-1">
              Welcome, {doctorInfo?.firstName || "Clinician"}
            </h1>
            <p className="text-muted-foreground">{doctorInfo?.specialization || "General Practice"} Registry</p>
          </div>
          <div className="flex items-center gap-3">
            <Button variant="outline" className="rounded-xl" onClick={() => router.push('/dashboard/doctor/schedule')}>
              <Calendar className="h-4 w-4 mr-2" /> My Schedule
            </Button>
            <Badge className="bg-green-100 text-green-700 p-2 font-bold uppercase tracking-widest text-[10px]">Session Active</Badge>
          </div>
        </header>

        {selectedPatient && (
          <Card className={`mb-8 rounded-[2.5rem] border-none shadow-xl animate-in slide-in-from-top-4 duration-500 overflow-hidden ${selectedPatient.status === 'Arrived' ? 'bg-red-50' : 'bg-yellow-50'}`}>
            <CardHeader className="border-b border-black/5 pb-6">
              <div className="flex justify-between items-center">
                <div className="flex items-center gap-4">
                  <div className={`p-4 rounded-2xl ${selectedPatient.status === 'Arrived' ? 'bg-red-600 text-white' : 'bg-yellow-500 text-white'}`}>
                    <AlertTriangle className="h-8 w-8" />
                  </div>
                  <div>
                    <CardTitle className="text-3xl font-headline">AI Risk Snapshot: {selectedPatient.patient}</CardTitle>
                    <CardDescription className="text-lg font-medium opacity-80">Pre-consultation intelligence generated by MediFlow AI.</CardDescription>
                  </div>
                </div>
                <Button variant="ghost" size="icon" onClick={() => setSelectedPatient(null)} className="rounded-full h-12 w-12 hover:bg-black/5">
                  <X className="h-6 w-6" />
                </Button>
              </div>
            </CardHeader>
            <CardContent className="pt-8">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div className="space-y-4">
                  <h5 className="font-bold uppercase tracking-widest text-xs text-muted-foreground flex items-center gap-2">
                    <TrendingUp className="h-4 w-4" /> Key Risk Factors
                  </h5>
                  <ul className="space-y-3 text-sm font-bold">
                    <li className="flex items-start gap-2"><div className="h-1.5 w-1.5 rounded-full bg-red-600 mt-1.5" />High (Family history of CVD)</li>
                    <li className="flex items-start gap-2"><div className="h-1.5 w-1.5 rounded-full bg-red-600 mt-1.5" />BP elevated over last 3 visits</li>
                    <li className="flex items-start gap-2"><div className="h-1.5 w-1.5 rounded-full bg-red-600 mt-1.5" />Allergy: Penicillin sensitive</li>
                  </ul>
                </div>
                <div className="space-y-4 border-l pl-8">
                  <h5 className="font-bold uppercase tracking-widest text-xs text-muted-foreground flex items-center gap-2">
                    <Activity className="h-4 w-4" /> Compliance Rate
                  </h5>
                  <div className="text-4xl font-black text-primary">82%</div>
                  <p className="text-xs text-muted-foreground">Adherence to previous medication course.</p>
                </div>
                <div className="flex flex-col justify-end">
                   <Button className="w-full h-16 text-xl rounded-2xl shadow-xl shadow-primary/20" onClick={() => handlePrescribe(selectedPatient.id)}>
                      Start Diagnostic Session
                      <ChevronRight className="ml-2 h-6 w-6" />
                   </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        <Card className="rounded-[2rem] border-none shadow-xl bg-white overflow-hidden">
          <CardHeader className="bg-slate-50 border-b pb-8 px-10">
            <CardTitle className="text-2xl">Today's Clinical Queue</CardTitle>
            <CardDescription>Verify patient arrival to initiate sessions.</CardDescription>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader className="bg-slate-50/50">
                <TableRow>
                  <TableHead className="pl-10 py-6 uppercase tracking-widest text-[10px] font-bold">Patient</TableHead>
                  <TableHead className="uppercase tracking-widest text-[10px] font-bold">Time</TableHead>
                  <TableHead className="uppercase tracking-widest text-[10px] font-bold">Status</TableHead>
                  <TableHead className="text-right pr-10 uppercase tracking-widest text-[10px] font-bold">Action</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {todayAppointments.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={4} className="text-center py-20 text-muted-foreground italic">No consultations today.</TableCell>
                  </TableRow>
                ) : (
                  todayAppointments.map((apt) => (
                    <TableRow key={apt.id} className="hover:bg-primary/5 transition-colors cursor-pointer group" onClick={() => setSelectedPatient(apt)}>
                      <TableCell className="pl-10 py-6 font-bold text-lg">{apt.patient}</TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Clock className="h-4 w-4 text-primary" />
                          <span className="font-medium">{apt.time}</span>
                        </div>
                      </TableCell>
                      <TableCell>
                         <Badge variant={apt.status === 'Arrived' ? 'default' : 'outline'} className="rounded-full px-4 font-bold">
                           {apt.status}
                         </Badge>
                      </TableCell>
                      <TableCell className="text-right pr-10">
                         {apt.status === 'Arrived' ? (
                           <Button className="rounded-xl px-6 font-bold" onClick={(e) => { e.stopPropagation(); handlePrescribe(apt.id); }}>
                              Diagnose
                           </Button>
                         ) : (
                           <Button 
                             variant="secondary" 
                             className="rounded-xl px-6 font-bold"
                             disabled={checkingIn === apt.id}
                             onClick={(e) => { e.stopPropagation(); handleCheckIn(apt.id); }}
                           >
                              {checkingIn === apt.id ? <Loader2 className="h-4 w-4 animate-spin" /> : "Verify Arrival"}
                           </Button>
                         )}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
